pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*

resources:
  repositories:
    - repository: templates
      type: github
      name: JPPGroup/IronstoneMeta
      endpoint: JPPGroup      
      
jobs:
- template: .ado/pipelinetemplates/buildtest.yml@templates  # Template reference
  parameters:
    SolutionName: 'IronstoneCore'    